# Form implementation generated from reading ui file 'C:\Users\PC\Downloads\HK2-2024-2025\ĐẠI HỌC\NĂM 3\HK1_2526\MACHINE LEARNING\ML_Pycharm\CodingPythonAPI\mainwindowAPITranslate.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 121, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 131, 21))
        self.label_3.setObjectName("label_3")
        self.lineEditInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditInput.setGeometry(QtCore.QRect(230, 30, 201, 20))
        self.lineEditInput.setObjectName("lineEditInput")
        self.comboBoxSource = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxSource.setGeometry(QtCore.QRect(230, 70, 201, 22))
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.comboBoxTarget = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxTarget.setGeometry(QtCore.QRect(230, 110, 201, 22))
        self.comboBoxTarget.setObjectName("comboBoxTarget")
        self.comboBoxTarget.addItem("")
        self.comboBoxTarget.addItem("")
        self.comboBoxTarget.addItem("")
        self.comboBoxTarget.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 160, 101, 21))
        self.pushButton.setObjectName("pushButton")
        self.labelKetqua = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelKetqua.setGeometry(QtCore.QRect(230, 200, 201, 21))
        self.labelKetqua.setObjectName("labelKetqua")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter text to translate:"))
        self.label_2.setText(_translate("MainWindow", "Choose source language:"))
        self.label_3.setText(_translate("MainWindow", "Choose target language:"))
        self.comboBoxSource.setItemText(0, _translate("MainWindow", "en"))
        self.comboBoxSource.setItemText(1, _translate("MainWindow", "es"))
        self.comboBoxSource.setItemText(2, _translate("MainWindow", "vn"))
        self.comboBoxSource.setItemText(3, _translate("MainWindow", "french"))
        self.comboBoxTarget.setItemText(0, _translate("MainWindow", "en"))
        self.comboBoxTarget.setItemText(1, _translate("MainWindow", "es"))
        self.comboBoxTarget.setItemText(2, _translate("MainWindow", "vn"))
        self.comboBoxTarget.setItemText(3, _translate("MainWindow", "french"))
        self.pushButton.setText(_translate("MainWindow", "Translate"))
        self.labelKetqua.setText(_translate("MainWindow", "TextLabel"))
